#+TITLE: Bayesian Statistics the Fun Way
#+OPTIONS: tex:t :export both
#+STARTUP: latexpreview

* Introduction

I have recently finished reading the very good book, 
[[https://nostarch.com/learnbayes]["Bayesian Statistics the Fun Way"]] by Will Kurt. This books 
is a concise introduction to Bayesian statistics. What I really
liked from this book is how it builds intuition of what
the statistics represent and what they measure.

One effective way to learn is to reflect about what you
have just learn. A typical tool for reflecting is to
do some exercise that implies using the new knowledge
you just learn.

The book contains a few exercises at the end of every
chapter and some of them require writing a brief script 
in R to solve it. Since I am more familiar with Python
programming and I would actually like to learn more
about the scipy.stats module I though it would be
fun to write my solutions to the exercises presented,
but this time in Python.

~NOTE: the actual solutions to the book problems can 
be found on the web for the book.~ [[https://nostarch.com/download/resources/Bayes_exercise_solutions.pdf][Solutions]]

* Solutions to the problems
** Chapter 4
This chapter presents the binomial distribution, that is
a generalization for solving problems of the type; 
~Determine the probability of k outcomes in n trials, where the 
probability of the outcome is p.~

$B(k;n,p) = {n \choose k} \times p^{k} \times (1 - p)^{n-k}$

[[file:bstfw_solutions_chapter_04.org::*Problems%20-%20chapter%204][Problems - chapter 4]]

** Chapter 5
