#+TITLE: Bayesian Statistics the Fun Way
#+OPTIONS: tex:t
#+STARTUP: latexpreview

* Introduction

I have recently finished reading the very good book, 
[[https://nostarch.com/learnbayes]["Bayesian Statistics the Fun Way"]] by Will Kurt. This books 
is a concise introduction to Bayesian statistics. What I really
liked from this book is how it builds intuition of what
the statistics represent and what they measure.

One effective way to learn is to reflect about what you
have just learn. A typical tool for reflecting is to
do some exercise that implies using the new knowledge
you just learn.

The book contains a few exercises at the end of every
chapter and some of them require writing a brief script 
in R to solve it. Since I am more familiar with Python
programming and I would actually like to learn more
about the scipy.stats module I though it would be
fun to write my solutions to the exercises presented,
but this time in Python.

~NOTE: the actual solutions to the book problems can 
be found on the web for the book.~ [[https://nostarch.com/download/resources/Bayes_exercise_solutions.pdf][Solutions]]

* Solutions to the problems
** Chapter 4
<b>Q1. What are the parameters of the binomial distribution 
for the probability of rolling either a 1 or a 20 on a 20-sided die, 
if we roll the die 12 times?</b>

Remember the parameters for the binomial distribution are
 - k number of outcomes we care about
 - n number of trial
 - p probability of the event happening

And the binomial distribution looks like this:


$B(k;n,p) = { n \choose k } \times p^k \times (1 - p)^{n-k}$

#+BEGIN_SRC python
from scipy.stats import binom

n=12
k=1
p=2./20  # two sides (1,20) of the 20 sided dice

#+END_SRC

<b>Q2. There are four aces in a deck of 52 cards. If you pull 
a card, return the card, then reshuffle and pull a card again,
how many ways can you pull just one ace in five pulls</b>

In Python the function choose is implemented in [[https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.misc.comb.html][scipy.misc.comb]]

#+BEGIN_SRC python
from scipy.special import comb

n=5
k=1
p=4./52  # 4 aces in the 52 card deck

return comb(5,1)

#+END_SRC

#+RESULTS:
: 5.0
Calling comb(5,1) returns 5 possible combinations;

 - A X X X X
 - X A X X X
 - X X A X X
 - X X X A X
 - X X X X A
